package Client;


public class Main {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Autogenerated method stub
		GUI_Main gui = new GUI_Main();
		gui.start();

	}	
}
